In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# 2D array
b = np.array([[1,2,3], [4,5,6]])

In [6]:
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3D array
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [8]:
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
# array dtype float
d = np.array([[1,2,3], [4,5,6]], dtype=float)

In [10]:
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
# array dtype bool
e = np.array([[0,2,3], [4,5,6]], dtype=bool)

In [12]:
e

array([[False,  True,  True],
       [ True,  True,  True]])

In [13]:
# arange 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# arange
np.arange(1,11 , 2)

array([1, 3, 5, 7, 9])

In [15]:
# reshape 
np.arange(1,11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
np.arange(1,11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
# ones
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
# zeros
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# np.random will generate between 0 to 1 numbers
np.random.random((2,5))

array([[0.24392011, 0.86502893, 0.09232572, 0.7883343 , 0.80566953],
       [0.88371003, 0.86433584, 0.43077452, 0.01259355, 0.08284475]])

In [20]:
np.linspace(2 , 20 , 5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [21]:
np.linspace(2,10,5 ,dtype=int)

array([ 2,  4,  6,  8, 10])

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy Array Attributes

In [24]:
a1 = np.arange(10)
a2 = np.arange(10 , dtype=float).reshape(5,2)
a3 = np.arange(8).reshape(4,2)

In [25]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a2

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [27]:
a3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [28]:
# ndim
a2.ndim

2

In [29]:
a1.shape

(10,)

In [30]:
a2.shape

(5, 2)

In [31]:
a3.shape

(4, 2)

In [32]:
a1.size

10

In [33]:
a2.size

10

In [34]:
a3.shape

(4, 2)

In [35]:
a1.itemsize

4

In [36]:
a2.itemsize

8

In [37]:
a3.itemsize

4

int32 takes 4 bytes and int64 takes 64 bytes

In [38]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


## Changing dtype

In [39]:
a1.astype(np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

## Array operations

In [40]:

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(3,4)

In [41]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Scalar operation

In [43]:
# arthemetic 
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [44]:
a2 + 2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [45]:
# relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
a2 < 17

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

#### vector operation

In [47]:
# arthemtic 
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [48]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [49]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

## Array functions

In [50]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)

In [51]:
a1

array([[94., 53., 19.,  6.],
       [45., 71., 84., 79.],
       [53., 35., 80.,  5.]])

In [52]:
# max , min , sum , prod
a1.min()

5.0

In [53]:
a1.max()

94.0

In [54]:
a1.sum()

624.0

In [55]:
a1.prod()

8.93490048238032e+18

In [56]:
# finding min number in row
a1.min(axis=1) 

array([ 6., 45.,  5.])

In [57]:
# finding max number in column
a1.max(axis=0)

array([94., 71., 84., 79.])

In [58]:
# mean , median , var
a1.mean()

52.0

In [59]:
np.median(a1)

53.0

In [60]:
a1.std()

29.46183972531247

In [61]:
np.var(a1)

868.0

#### trigometric function

In [62]:
np.sin(a1)

array([[-0.24525199,  0.39592515,  0.14987721, -0.2794155 ],
       [ 0.85090352,  0.95105465,  0.73319032, -0.44411267],
       [ 0.39592515, -0.42818267, -0.99388865, -0.95892427]])

In [63]:
np.cos(a1)

array([[ 0.96945937, -0.91828279,  0.98870462,  0.96017029],
       [ 0.52532199, -0.30902273, -0.6800235 , -0.89597095],
       [-0.91828279, -0.90369221, -0.11038724,  0.28366219]])

In [64]:
np.tan(a1)

array([[-0.2529781 , -0.4311582 ,  0.15158947, -0.29100619],
       [ 1.61977519, -3.0776204 , -1.07818381,  0.49567753],
       [-0.4311582 ,  0.47381472,  9.00365495, -3.38051501]])

In [65]:
# dot function
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12, 24).reshape(4,3)

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [68]:
np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [69]:
# log and exponents
np.log(a1)

array([[4.54329478, 3.97029191, 2.94443898, 1.79175947],
       [3.80666249, 4.26267988, 4.4308168 , 4.36944785],
       [3.97029191, 3.55534806, 4.38202663, 1.60943791]])

In [70]:
np.exp(a1)

array([[6.66317622e+40, 1.04137594e+23, 1.78482301e+08, 4.03428793e+02],
       [3.49342711e+19, 6.83767123e+30, 3.02507732e+36, 2.03828107e+34],
       [1.04137594e+23, 1.58601345e+15, 5.54062238e+34, 1.48413159e+02]])

In [71]:
# round , floor , ceil
np.random.random((3, 4))*100

array([[27.74878261, 40.74972445, 25.86787747, 18.31406653],
       [38.3458085 , 57.23379728, 93.40378293, 81.83054524],
       [16.19256859, 47.66397648, 76.82970789,  2.87828921]])

In [72]:
np.round(np.random.random((3, 4))*100)

array([[53., 57., 24., 34.],
       [ 5., 53., 51., 68.],
       [71., 43., 17., 14.]])

In [73]:
np.floor(np.random.random((3, 4))*100)

array([[ 6., 47.,  9., 22.],
       [ 9.,  3., 70., 50.],
       [57., 22., 72., 20.]])

In [74]:
np.ceil(np.random.random((3, 4))*100)

array([[28., 10., 27., 42.],
       [90., 71., 99., 27.],
       [63., 57., 93., 40.]])

## indexing and slicing

#### indexing

In [75]:
a1 = np.arange(12)
a2 = np.arange(12, 24).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [76]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
a1[-1]

11

In [78]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [79]:
# find 18
a2[1,2]

18

In [80]:
# find 23
a2[2,3]

23

In [81]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [82]:
# finding 5
a3[1, 0 , 1]

5

In [83]:
# finding 6
a3[1,1,0]

6

In [84]:
# finding 2
a3[0, 1,0]

2

In [85]:
# finding 0
a3[0,0,0]

0

#### slicing

In [86]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:

a1[2:7]

array([2, 3, 4, 5, 6])

In [88]:
a1[2:7:2]

array([2, 4, 6])

In [89]:
 a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
a2[0:1]

array([[12, 13, 14, 15]])

In [91]:
a2[1:-1]

array([[16, 17, 18, 19]])

In [92]:
# finding 17 ,18 and 21 ,22
a2[1:,1:3]

array([[17, 18],
       [21, 22]])

In [93]:
a2[1:,2:]

array([[18, 19],
       [22, 23]])

In [94]:
a2[::2,::3]

array([[12, 15],
       [20, 23]])

In [95]:
a2[:3:2,1::2]

array([[13, 15],
       [21, 23]])

In [96]:
a2[1,::3]

array([16, 19])

In [97]:
a3 = np.arange(27).reshape(3,3,3)

In [98]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [100]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a3[0,1]

array([3, 4, 5])

In [102]:
a3[1,:,1]

array([10, 13, 16])

In [103]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [104]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [105]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [106]:
a2
for i in a2:
    print(i)

[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [107]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [108]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [109]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshape

In [110]:
# transpose
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [111]:
a2.transpose()

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [112]:
# ravel
a2.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [113]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## stacking

In [114]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [115]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [117]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## splitting

In [118]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [120]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [122]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]